// Generated by CoffeeScript 1.7.1
(function() {
  var CHR, TRM, echo, log, rpr;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  log = TRM.log.bind(TRM);

  echo = TRM.echo.bind(TRM);

  CHR = require('coffeenode-chr');

  this.translations = require('./translations');

  this.get_languagecode_and_translator_with_fallback = function(languagecode) {
    var error, translator;
    try {
      translator = this.get_translator(languagecode);
    } catch (_error) {
      error = _error;
      if ((error['message'].match(/^unknown locale specifier: /)) == null) {
        throw error;
      }
      languagecode = 'en_US';
      translator = this.get_translator(languagecode);
    }
    return [languagecode, translator];
  };

  this.get_translator = function(languagecode) {
    var fallback_languagecode, fallback_translations, is_valid, translations;
    fallback_languagecode = 'en_US';
    translations = this.translations[languagecode];
    fallback_translations = this.translations[fallback_languagecode];
    is_valid = function(translation) {
      return (translation != null) && translation.length > 0;
    };
    if (translations == null) {
      throw Error("unknown locale specifier: " + (rpr(languagecode)));
    }
    return (function(_this) {
      return function(text) {
        var R;
        R = translations[text];
        if ((languagecode !== fallback_languagecode) && (!is_valid(R))) {
          R = fallback_translations[text];
        }
        if (!is_valid(R)) {
          R = text;
        }
        return R;
      };
    })(this);
  };

}).call(this);
