// Generated by CoffeeScript 1.12.1
(function() {
  var TRM, alert, badge, echo, info, log, njs_cp, njs_fs, njs_path, route, rpr, source, warn, whisper;

  njs_fs = require('fs');

  njs_path = require('path');

  njs_cp = require('child_process');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'postprocess';

  echo = TRM.echo.bind(TRM);

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  warn = TRM.get_logger('warn', badge);


  /* This is a kludgy hack to bring TAGTOOL to the web. Awaiting a real solution. */

  route = './public/coffeenode-tagtool/main.js';

  source = njs_fs.readFileSync(route, {
    encoding: 'utf-8'
  });

  source = source.replace(/(\/\/ Generated by CoffeeScript 1.6.3)/, "$1\nvar TAGTOOL = {};\n");

  source = source.replace('\n}).call(this);', "}).call(TAGTOOL);\n");

  njs_fs.writeFileSync(route, source, {
    encoding: 'utf-8'
  });

  echo('TAGTOOL source converted');

}).call(this);
